"""empty message

Revision ID: 03e2dd1d2a99
Revises: 5b626b64294b
Create Date: 2020-05-02 23:17:23.563315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03e2dd1d2a99'
down_revision = '5b626b64294b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('detail', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'detail')
    # ### end Alembic commands ###
