"""empty message

Revision ID: 5b626b64294b
Revises: 723e8e2d759c
Create Date: 2020-05-02 22:22:20.935285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b626b64294b'
down_revision = '723e8e2d759c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_medicine',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('planid', sa.String(length=64), nullable=True),
    sa.Column('medicineid', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_medicine')
    # ### end Alembic commands ###
