"""empty message

Revision ID: 723e8e2d759c
Revises: 7e036a74bd49
Create Date: 2020-05-02 17:40:24.986974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '723e8e2d759c'
down_revision = '7e036a74bd49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicine', sa.Column('sale', sa.String(length=12), nullable=True))
    op.add_column('plans', sa.Column('illness', sa.String(length=128), nullable=True))
    op.add_column('plans', sa.Column('total_sale', sa.String(length=24), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'total_sale')
    op.drop_column('plans', 'illness')
    op.drop_column('medicine', 'sale')
    # ### end Alembic commands ###
